Repository mafia-together/frontend, pull requests merged in 2024-05, with the labels that each got.

#23 [feat] 채팅 기능 구현 (Polling)
  .eslintrc.cjs
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/axios/http.ts
  src/axios/instances.ts
  src/components/chat/ChatGroup.tsx
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatMessage.tsx
  src/components/chat/Chats.tsx
  src/components/player/PlayerChat.tsx
  src/components/test/ParticipateRoom.ts
  src/main.tsx
  src/pages/Day.tsx
  src/styles/VariablesCSS.ts
  src/type/index.ts
Labels: feat

#25 [refactor] onClick() Event를 form 태그 내부의 input 태그로 옮긴다.
  src/components/chat/ChatInput.tsx
Labels: refactor

#61 [refactor] 최종 결과 화면을 구현한다.
  src/axios/http.ts
  src/components/modal/InvestResult.tsx
  src/components/player/PlayerInvest.tsx
  src/components/player/PlayerResult.tsx
  src/pages/InputCode.tsx
  src/pages/Result.tsx
  src/type/index.ts
Labels: feat, refactor

#67 hotfix: 모바일 크롬에서 vh계산하는 방법을 초기와 resize될때를 구분한다.
  src/App.tsx
Labels: hotfix
